version: "3"

dotenv: ['.env']

silent: true

########################################################################################################################
#
# TOC
#
########################################################################################################################
#
# 1. COMPOSER
# 2. MISCELLANEOUS
#
########################################################################################################################

tasks:
  ######################################################################################################################
  #
  #  1. COMPOSER
  #
  ######################################################################################################################

  c:update:
    desc: Run composer update
    cmds:
      - task: c:exec
        vars:
          SUBCMD: update

  c:install:
    desc: Run composer install
    cmds:
      - task: c:exec
        vars:
          SUBCMD: install

  c:exec:
    preconditions:
      - sh: test '{{.SUBCMD}}' = 'install' -o '{{.SUBCMD}}' = 'update'
        msg: SUBCMD value needs to be either 'install' or 'update'
    cmds:
      - docker volume create php_composer_cache
      - docker run
        --interactive
        --tty
        --rm
        --volume "$(pwd)":/var/www
        --volume php_composer_cache:/home/composer/.composer
        --entrypoint ''
        -e COMPOSER_HOME=/home/composer/.composer
        ilyes512/php80-fpm:builder-latest
        composer {{.SUBCMD}}
        --no-progress
        --prefer-dist
        --ignore-platform-reqs

  ######################################################################################################################
  #
  #  2. MISCELLANEOUS
  #
  ######################################################################################################################

  dc:down:
    desc: Cleanup Devcontainer including volumes
    cmds:
      - docker-compose
        -f .devcontainer/docker-compose.yml
        down --volumes

  cleanup:
    desc: Cleanup generated files and vendor files
    cmds:
      - rm -rf
        vendor
        composer.lock
        .phplint-cache
        && printf "%s\n" "Successfully removed vendor/generated files..."
