version: "3.7"
services:
  php:
    image: signet/ecs/php/vscode:latest
    entrypoint: ["sh", "-c", "trap : 15 ; sleep 9999d & wait"]
    build:
      context: ../.
      dockerfile: .devcontainer/Dockerfile
      args:
        IMAGE_TAG_PHP_VSCODE: ${IMAGE_TAG_PHP_VSCODE:-vscode-latest}
    volumes:
      - $HOME/.ssh/known_hosts:/home/code/.ssh/known_hosts:ro
      # - $HOME/auth.json:/root/auth.json:ro
      - ../.:/workspace:delegated
      - vscode-extensions:/home/code/.vscode-server/extensions

volumes:
  vscode-extensions:
